"""Add DocumentoDigitalizado columns

Revision ID: 42e78a13ac11
Revises: 
Create Date: 2026-05-14 19:53:12.274398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42e78a13ac11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento_digitalizado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('dados', sa.LargeBinary(), nullable=False))
        batch_op.add_column(sa.Column('mimetype', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('veiculo_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'veiculo', ['veiculo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento_digitalizado', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('veiculo_id')
        batch_op.drop_column('mimetype')
        batch_op.drop_column('dados')
        batch_op.drop_column('nome')

    # ### end Alembic commands ###